## Numpy Basics  

In [2]:
import numpy as np

Creating array from lists

In [ ]:
arr_1d = np.array([1,2,3,4,5,6])
print("1D Array: ", arr_1d)

arr_2d = np.array([[1,2,3], [4,5,6]])
print("2D Array: ", arr_2d)

1D Array:  [1 2 3 4 5 6]
2D Array:  [[1 2 3]
 [4 5 6]]


LIST VS NUMPY

In [5]:
py_list = [1,2,3]
print("Python List Multiplication: ", py_list*2)

np_array = np.array([1,2,3])
print("Python Array Multiplication: ", np_array*2)

import time
start = time.time()
py_list = [i*2 for i in range(100000)]
print("\n List Operation Time= ", time.time() - start)

start = time.time()
np_array = np.arange(100000)
print("\n Numpy Operation Time= ", time.time() - start)

Python List Multiplication:  [1, 2, 3, 1, 2, 3]
Python Array Multiplication:  [2 4 6]

 List Operation Time=  0.009868860244750977

 Numpy Operation Time=  0.0011000633239746094


### Creating Array From Scratch

In [14]:
"""zeros = np.zeros((3,4))
print("zeros array: \n", zeros)

ones = np.ones((3,2))
print("ones array: \n", ones)

full = np.full((2,2), 6)
print("full array: \n", full)"""

random = np.random.random((3,3))
print("random Array: \n", random)

sequence = np.arange(0, 15, 2)
print("Sequence: \n", sequence)

random Array: 
 [[0.72625338 0.39510726 0.80065956]
 [0.52040925 0.8051946  0.00954179]
 [0.84746384 0.93830758 0.67611211]]
Sequence: 
 [ 0  2  4  6  8 10 12 14]


VECTOR, MATRIX & TENSOR

In [18]:
vector = np.array([1,2,3,4])
print("Vector: ",vector)

matrix = np.array([[1,2,3], [4,5,6]])
print("Matrix: \n",matrix)

tensor = np.array([[[1,2], [2,3], [3,4]],
                   [[5,6], [7,8], [9,10]]])
print("Tensor: \n", tensor)

Vector:  [1 2 3 4]
Matrix: 
 [[1 2 3]
 [4 5 6]]
Tensor: 
 [[[ 1  2]
  [ 2  3]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]
  [ 9 10]]]


### Array Properties

In [23]:
arr = np.array([[1,2,3],
                [4,5,6]])
print("Shape of array: ", arr.shape)
print("Dimension: ", arr.ndim)
print("size: ", arr.size)
print("Dtype: ", arr.dtype)

Shape of array:  (2, 3)
Dimension:  2
size:  6
Dtype:  int64


ARRAY Reshaping

In [ ]:
arr = np.arange(10)
print("original array:", arr)

reshaped = arr.reshape((5,2))
print("Reshaped Array: ", reshaped)

flattened = reshaped.flatten()
print("\n Flattened Array: ", flattened)

# ravel returns view, instead of copy
raveled = reshaped.ravel()
print("Raveled Array: ", raveled)

# Transpose
transpose = reshaped.T
print("Transposed Array: \n", transpose)

original array: [0 1 2 3 4 5 6 7 8 9]
Reshaped Array:  [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]

 Flattened Array:  [0 1 2 3 4 5 6 7 8 9]
Raveled Array:  [0 1 2 3 4 5 6 7 8 9]
Transposed Array: 
 [[0 2 4 6 8]
 [1 3 5 7 9]]
