NUMPY ARRAY OPERATIONS

In [1]:
import numpy as np

In [3]:
arr = np.array([1,2,3,4,5,6])
print("Basic slicing: ", arr[2:4])

print("With step: ", arr[1:6:2])
print("Negative Indexing: ", arr[-3])

Basic slicing:  [3 4]
With step:  [2 4 6]
Negative Indexing:  4


In [9]:
arr_2d = np.array([[1,2,3], [4,5,6], [7,8,9]])
print("Specific Element: ", arr_2d[1,2])
print("Entire row: ", arr_2d[2])
print("Entire column: ", arr_2d[:,1])

Specific Element:  6
Entire row:  [7 8 9]
Entire column:  [2 5 8]


## Sorting

In [12]:
unsorted = np.array([3,7,2,0,5,9,1,6,0])
print("Sorted Array: ", np.sort(unsorted))

arr_2d_unsorted = np.array([[3,5], [2,6], [2,1]])
print("Sorted 2D array by column: ", np.sort(arr_2d_unsorted, axis=0))
print("Sorted 2D array by row: ", np.sort(arr_2d_unsorted, axis=1))

Sorted Array:  [0 0 1 2 3 5 6 7 9]
Sorted 2D array by column:  [[2 1]
 [2 5]
 [3 6]]
Sorted 2D array by row:  [[3 5]
 [2 6]
 [1 2]]


## FILTER

In [17]:
nums = np.array([1,2,3,4,5,6,7,8,9,10])
even_nums = nums[nums%2 == 0]
print("Even Nums: ",even_nums)
odd_nums = nums[nums%2 != 0]
print("Odd Nums: ", odd_nums)

# Filter with mask
mask = nums > 5
print("Nums > 5: ", nums[mask])

Even Nums:  [ 2  4  6  8 10]
Odd Nums:  [1 3 5 7 9]
Nums > 5:  [ 6  7  8  9 10]


Fancy Indexing vs np.where()

In [19]:
indices = [0,2,4]
print(nums[indices])

where_result = np.where(nums < 5)
print("NP where: ", nums[where_result])

[1 3 5]
NP where:  [1 2 3 4]


In [23]:
condition_array = np.where(nums > 6, "1", "2")
print(condition_array)

['2' '2' '2' '2' '2' '2' '1' '1' '1' '1']


Add & Remove Data

In [25]:
arr1 = np.array([1,3,5])
arr2 = np.array([2,4,6])
combined = np.concatenate((arr1, arr2)) # incorrect way -> arr1 + arr2
print(combined)

[1 3 5 2 4 6]


Array Compatibility

In [28]:
a = np.array([2,4,6])
b = np.array([1,3,5,7])
c = np.array([7,8,9])
print("Compatibility Shapes: ", a.shape == b.shape)

Compatibility Shapes:  False


In [31]:
og = np.array([[1,2], [3,4], [5,6]])
new_row = np.array([[7,8]])

with_new_row = np.vstack((og ,new_row))
print("With new Row: ", with_new_row)

new_col = np.array([[9], [10], [11]])
with_new_col = np.hstack((og , new_col))
print("With new Column: ", with_new_col)

With new Row:  [[1 2]
 [3 4]
 [5 6]
 [7 8]]
With new Column:  [[ 1  2  9]
 [ 3  4 10]
 [ 5  6 11]]


DELETE

In [34]:
arr = np.array([1,2,3,4,5])
deleted = np.delete(arr, 3) # array after deletion
print("Array after deletion: ",deleted)

Array after deletion:  [1 2 3 5]
